GrupoCero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('artistas/', artistas, name="artistas"), 
    path('adminsindex/', adminsindex, name="adminsindex"),
    path('adminsolicitudes/', adminSolicitudes, name="adminsolicitudes"),
    path('adminsolicitudesartistas/', adminSolicitudesArtistas, name="adminsolicitudesartistas"),
    path('adminsolicitudeslanzamientos/', adminSolicitudesLanzamientos, name="adminsolicitudeslanzamientos"),
    path('adminsolicitudestipolanzamientos/', adminSolicitudesTipoLanzamientos, name="adminsolicitudestipolanzamientos"),
    path('adminsolicitudesgeneros/', adminSolicitudesGeneros, name="adminsolicitudesgeneros"),
    path('adminsaprobar/', adminsaprobar, name="adminsaprobar"),    
    path('loginadmins/', loginadmins, name="loginadmins"),
    path('loginadmin/', loginadmin, name="loginadmin"),
    path('lanzamientos/', lanzamientos, name="lanzamientos"), 
    path('loginmiembros/', loginmiembros, name="loginmiembros"),
    path('miembrosindex/', miembrosindex, name="miembrosindex"),
    path('login/', logincliente, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registercliente, name='registercliente'),
    path('registermiembro/', registermiembro, name='registermiembro'),
    path('loginmiembro/', loginmiembro, name='loginmiembro'),
    path('addtipolanzamientos/', addtipolanzamientos, name='addtipolanzamientos'),
    path('generosobjects/', generosobjects, name='generosobjects'),
    path('generosadd/', generosadd, name='generosadd'),
    path('generosdelete/<int:id>/', generosdelete, name='generosdelete'),
    path('generosupdate/<int:id>/', generosupdate, name='generosupdate'),
    path('artistasobjects/', artistasobjects, name='artistasobjects'),
    path('artistasadd/', artistasadd, name='artistasadd'),
    path('artistasdelete/<int:id>/', artistasdelete, name='artistasdelete'),
    path('artistasupdate/<int:id>/', artistasupdate, name='artistasupdate'),
    path('tipolanzamientosobjects/', tipolanzamientosobjects, name='tipolanzamientosobjects'),
    path('tipolanzamientossadd/', tipolanzamientosadd, name='tipolanzamientosadd'),
    path('tipolanzamientosdelete/<int:id>/', tipolanzamientosdelete, name='tipolanzamientosdelete'),
    path('tipolanzamientosupdate/<int:id>/', tipolanzamientosupdate, name='tipolanzamientosupdate'),
    path('lanzamientosobjects/', lanzamientosobjects, name='lanzamientosobjects'),
    path('lanzamientosadd/', lanzamientosadd, name='lanzamientosadd'),
    path('lanzamientosdelete/<int:id>/', lanzamientosdelete, name='lanzamientosdelete'),
    path('lanzamientosupdate/<int:id>/', lanzamientosupdate, name='lanzamientosupdate'),

]

core/models.py
from django.db import models
from django import forms

import datetime

# Create your models here.
    
TIPO_APROBACION = [
    ('aprobado', 'Aprobado'),
    ('pendiente', 'Pendiente'),
    ('rechazado', 'Rechazado')
]


class TipoLanzamiento(models.Model):
    nombreTipo = models.CharField(max_length=20)
    aprobado = models.CharField(max_length=20, choices=TIPO_APROBACION, default='pendiente')
    fecha_solicitud = models.DateField(null=True, blank=True, default=datetime.date.today)  
    feedback = models.TextField(blank=True)

    def __str__(self):
        return self.nombreTipo
    
    class Meta:
        verbose_name = "Tipo de lanzamiento"
        verbose_name_plural = "Tipos de lanzamiento"

class Artista(models.Model):
    nombreArtista = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    biografia = models.TextField()
    imagen = models.ImageField(upload_to='artistas/', null=False, blank=False)
    aprobado = models.CharField(max_length=20, choices=TIPO_APROBACION, default='pendiente')
    fecha_solicitud = models.DateField(null=True, blank=True, default=datetime.date.today)
    feedback = models.TextField(blank=True)

    def clean_imagen(self):
        imagen = self.cleaned_data.get('imagen')
        if not imagen:
            raise forms.ValidationError("Este campo es obligatorio.")
        return imagen

    def __str__(self):
        return self.nombreArtista
    
    class Meta:
        verbose_name = "Artista"
        verbose_name_plural = "Artistas"
    
class GeneroMusical(models.Model):
    nombreGenero = models.CharField(max_length=30)
    aprobado = models.CharField(max_length=20, choices=TIPO_APROBACION, default='pendiente')
    fecha_solicitud = models.DateField(null=True, blank=True, default=datetime.date.today)  
    feedback = models.TextField(blank=True)

    def __str__(self):
        return self.nombreGenero
    
    class Meta:
        verbose_name = "Género Musical"
        verbose_name_plural = "Géneros Musicales"

class Lanzamiento(models.Model):
    tipoLanzamiento = models.ForeignKey(TipoLanzamiento, on_delete=models.CASCADE)
    nombreLanzamiento = models.CharField(max_length=50)
    artista = models.ForeignKey(Artista, on_delete=models.CASCADE)
    fechaLanzamiento = models.DateField()
    genero = models.ForeignKey(GeneroMusical, on_delete=models.CASCADE)
    descripcionLanzamiento = models.TextField()
    precio = models.IntegerField(default=0)
    imagen = models.ImageField(upload_to='lanzamientos/', null=True, blank=True)
    aprobado = models.CharField(max_length=20, choices=TIPO_APROBACION, default='pendiente')
    fecha_solicitud = models.DateField(null=True, blank=True, default=datetime.date.today)  
    feedback = models.TextField(blank=True)

    def __str__(self):
        return self.nombreLanzamiento
    
    def precio_clp(self):
        return "${:,.0f}".format(self.precio).replace(",", ".")
    
    class Meta:
        verbose_name = "Lanzamiento"
        verbose_name_plural = "Lanzamientos"


    

core/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.core.serializers import serialize

# Create your views here.
def index (request):
    context = {
        'listaArtistas' : Artista.objects.filter(aprobado='aprobado')[:4],
        'listaLanzamientos' : Lanzamiento.objects.filter(aprobado='aprobado')[:4]
    }

    return render(request, 'core/index.html', context)

def artistas (request):
    auxArtObj = {
        'listaArtObj' : Artista.objects.filter(aprobado='aprobado')
    }

    return render(request, 'core/artistas.html', auxArtObj)

def lanzamientos (request):
    auxLanzObj = {
        'listaLanzObj' : Lanzamiento.objects.filter(aprobado='aprobado')
    }

    return render(request, 'core/lanzamientos.html', auxLanzObj)

def loginmiembros (request):
    return render(request, 'core/miembros/loginMiembros.html')

def miembrosindex(request):
    return render(request, 'core/miembros/miembrosIndex.html')

def addtipolanzamientos (request):
    return render(request, 'core/miembros/tipoLanzamientos/crud/add.html')

def addgeneros (request):
    return render(request, 'core/miembros/generos/crud/add.html')

def adminsindex (request): 
    context = {
        'solicitudes' : Artista.objects.filter(aprobado='pendiente').values('id', 'fecha_solicitud', 'nombreArtista', 'aprobado'),
    }
    return render(request, 'core/admins/adminsIndex.html', context)

def adminSolicitudes (request):
    context = {
        'Artistas' : Artista.objects.filter(aprobado='pendiente'),
        'Lanzamientos' : Lanzamiento.objects.filter(aprobado='pendiente'),
        'Generos' : GeneroMusical.objects.filter(aprobado='pendiente'),
        'TiposLanzamientos' : TipoLanzamiento.objects.filter(aprobado='pendiente')
    }
    
    return render(request, 'core/admins/adminsSolicitudes.html', context)

def adminSolicitudesArtistas (request):
    id = request.GET.get('id')
    artista = Artista.objects.filter(id=id).first()
    context = {
        'Artista' : artista
    }
    return render(request, 'core/admins/adminsSolicitudesArtistas.html', context)

def adminSolicitudesLanzamientos (request):
    id = request.GET.get('id')
    lanzamiento = Lanzamiento.objects.filter(id=id).first()
    context = {
        'Lanzamiento' : lanzamiento
    }
    return render(request, 'core/admins/adminsSolicitudesLanzamientos.html', context)

def adminSolicitudesTipoLanzamientos (request):
    id = request.GET.get('id')
    print(id)
    tipolanzamiento = TipoLanzamiento.objects.filter(id=id).first()
    context = {
        'TipoLanzamiento' : tipolanzamiento
    }
    return render(request, 'core/admins/adminsSolicitudesTipoLanzamientos.html', context)

def adminSolicitudesGeneros (request):
    id = request.GET.get('id')
    genero = GeneroMusical.objects.filter(id=id).first()
    context = {
        'Genero' : genero
    }
    return render(request, 'core/admins/adminsSolicitudesGeneros.html', context)

def adminsaprobar (request):
    if request.method == 'POST':
        print(request.POST)
        id = request.POST.get('id')
        tipo = request.POST.get('tipo')
        estado = request.POST.get('aprobado')
        feedback = request.POST.get('feedback')

        match tipo:
            case 'artista':
                print(request.POST)
                artista = Artista.objects.filter(id=id).first()
                artista.aprobado = estado
                artista.feedback = feedback
                artista.save()
            case 'lanzamiento':
                print(request.POST)
                lanzamiento = Lanzamiento.objects.filter(id=id).first()
                lanzamiento.aprobado = estado
                lanzamiento.feedback = feedback
                lanzamiento.save()
            case 'genero':
                print(request.POST)
                genero = GeneroMusical.objects.filter(id=id).first()    
                genero.aprobado = estado
                genero.save()
            case 'TipoLanzamiento':
                print(request.POST)
                tipolanzamiento = TipoLanzamiento.objects.filter(id=id).first()
                tipolanzamiento.aprobado = estado
                tipolanzamiento.feedback = feedback
                tipolanzamiento.save()

        return redirect('adminsolicitudes')
    return render(request, 'adminsolicitudes')

def loginadmins (request):
    return render(request, 'core/admins/loginAdmins.html')

# LOGIN 

def logincliente(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            if user.groups.filter(name='clientes').exists():
                login(request, user)
                return redirect('index')
            elif user.groups.filter(name='miembros').exists():
                messages.error(request, 'Solo los clientes pueden iniciar sesión en este sitio.')
                return redirect('index')
        else:
            messages.error(request, 'Credenciales de inicio de sesión incorrectas.')
            return redirect('index')

    return render(request, 'index')

def logout_view(request):
    logout(request)
    return redirect('index')  

def loginmiembro(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        try:
            user = User.objects.get(email=email)
            username = user.username
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                if user.groups.filter(name='miembros').exists():
                    login(request, user)
                    return redirect('miembrosindex')
                elif user.groups.filter(name='clientes').exists():
                    messages.error(request, 'Solo los miembros pueden iniciar sesión en este sitio.')
                    return redirect('loginmiembros')
            else:
                messages.error(request, 'Credenciales de inicio de sesión incorrectas.')
                return redirect('loginmiembros')
        
        except User.DoesNotExist:
            messages.error(request, 'No existe un usuario con ese correo electrónico.')
            return redirect('loginmiembros')
    
    return render(request, 'loginmiembros')

def loginadmin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            if user.groups.filter(name='administradores').exists():
                login(request, user)
                return redirect('adminsindex') 
            elif user.groups.filter(name='clientes').exists():
                messages.error(request, 'Solo los administradores pueden iniciar sesión en este sitio.')
                return redirect('loginadmins')
            elif user.groups.filter(name='miembros').exists():
                messages.error(request, 'Solo los administradores pueden iniciar sesión en este sitio.')
        else:
            messages.error(request, 'Credenciales de inicio de sesión incorrectas.')
            return redirect('loginadmins')

    return render(request, 'loginadmins')  

# REGISTRO

def registercliente(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password']
        password2 = request.POST['password_confirmation']

        if password1 != password2:
            messages.error(request, 'Las contraseñas no coinciden.')
            return redirect('index')
        elif len(password1) < 8:
            messages.error(request, 'La contraseña debe tener al menos 8 caracteres.')
            return redirect('index')
        elif len(username) < 3:
            messages.error(request, 'El nombre de usuario debe tener al menos 3 caracteres.')
            return redirect('index')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'El nombre de usuario ya está en uso.')
            return redirect('index')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'El correo electrónico ya está en uso.')
            return redirect('index')
        else:
            user = User.objects.create_user(username=username, email=email, password=password1)
            cliente_group = Group.objects.get(name='clientes')
            user.groups.add(cliente_group)
            user.save()
            messages.success(request, 'Usuario creado correctamente')
            return redirect('index')

    return render(request, 'index')

# TIPO LANZAMIENTOS
def tipolanzamientosobjects(request):
    auxTipoObj = {
        'listaTipoObj' : TipoLanzamiento.objects.all()
    }

    return render(request, 'core/miembros/tipoLanzamientos/tipolanzamientosobjects.html', auxTipoObj)

def tipolanzamientosadd(request):
    aux = {
        'form': TipoLanzamientoForm()
    }

    if request.method == 'POST':
        formulario = TipoLanzamientoForm(request.POST)
        print(formulario.is_valid())
        if formulario.is_valid():
            formulario.save()
            aux['msj'] = "Tipo lanzamiento guardado correctamente!"
        else:
            aux['form'] = formulario
            aux['msj'] = "¡Error al guardar el tipo de lanzamiento!"

    return render(request, 'core/miembros/tipoLanzamientos/crud/add.html', aux)

core/templates/core/miembros/artistas/crud/add.html
<!DOCTYPE html>
<html lang="es">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel Miembro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'core/img/noise2.png' %}">
</head>
<body>

<!-- Inicio menú de admin con logo -->
<nav class="navbar navbar-expand-sm bg-light navbar-light justify-content-center">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'miembrosindex' %}">
            <img src="{% static 'core/img/LOGO.png' %}" alt="Avatar Logo" style="width:200px;" class="rounded-pill"> 
        </a>
    </div>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-center" style="width:200px;">Bienvenido, {{ user.username }}</a>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <button class="btn btn-dark" type="button" style="width:120px;">Cerrar sesión</button>
            </a>
        </li>
    </ul> 
</nav>

<!-- Form -->
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Agregar artista</h3>
                </div>
                <div class="card-body">
                    <form id="artistaForm" action="{% url 'artistasadd' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre del artista:</label>
                            {{ form.nombreArtista }}
                        </div>
                        <div class="mb-3">
                            <label for="fecha_nacimiento" class="form-label">Fecha de Nacimiento:</label>
                            {{ form.fecha_nacimiento }}
                        </div>
                        <div class="mb-3">
                            <label for="biografia" class="form-label">Biografía:</label>
                            {{ form.biografia }}
                        </div>
                        <div class="mb-3">
                            <label for="imagen" class="form-label">Imagen:</label>
                            {{ form.imagen }}
                        </div>
                        <input class="btn btn-dark" type="submit" value="Guardar">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'core/js/funciones.js' %}"></script>
{% include 'core/sweetalert.html' %}

</html>

core/templates/core/miembros/artistas/crud/update.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar Género Musical</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'core/img/noise2.png' %}">
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light justify-content-center">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'miembrosindex' %}">
            <img src="{% static 'core/img/LOGO.png' %}" alt="Avatar Logo" style="width:200px;" class="rounded-pill"> 
        </a>
    </div>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-center" style="width:200px;">Bienvenido, {{ user.username }}</a>
        </li>
    </ul>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <button class="btn btn-dark" type="button" style="width:120px;">Cerrar sesión</button>
            </a>
        </li>
    </ul> 
</nav>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Modificar artista</h3>
                </div>
                <div class="card-body">
                    <form id="artistaForm" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_nombreArtista" class="form-label">Nombre del artista:</label>
                            {{ form.nombreArtista }}
                        </div>
                        <div class="mb-3">
                            <label for="id_fecha_nacimiento" class="form-label">Fecha de Nacimiento:</label>
                            {{ form.fecha_nacimiento }}
                        </div>
                        <div class="mb-3">
                            <label for="id_biografia" class="form-label">Biografía:</label>
                            {{ form.biografia }}
                        </div>
                        <div class="mb-3">
                            <label for="imagen" class="form-label">Imagen:</label>
                            {{ form.imagen }}
                        </div>
                        <input class="btn btn-dark" type="submit" value="Guardar">
                        <a href="#" class="btn btn-dark" onclick="history.back()">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'core/js/funciones.js' %}"></script>
</body>
</html>